  
name: Docker Image CI

on:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        docker version
        # 登录阿里云镜像仓库
        docker login --username=${{ secrets.DOCKERZH }} --password=${{ secrets.DOCKERKEY }}
        # 使用Dockerfile构建镜像
        DOCKER_BUILDKIT=1 docker build -f deploy/docker/Dockerfile -t lowcoder-ce .
        # 推送镜像到镜像仓库
        docker push lowcoder-ce
